### ISSUE TITLE
please update api version 1.14.x

### ISSUE THREAD

**Issue by successed** [lishid/OpenInv#102]
Can you update api version 1.14.x please ?

in console log :

`[Server thread/WARN]: Plugin OpenInv v4.0.1 does not specify an api-version.`

**Comment by Jikoo** [comment]
What features specific to the 1.14 API is OpenInv lacking? OpenInv does not specify an API-version because the core plugin is compiled targeting the 1.8.8 API to maintain backwards compatibility with that version.

**Comment by Jikoo** [comment]
Never mind, api-version below 1.13 isn't allowed to load. If it's a problem for you, you can either configure your logger to ignore that particular line or include it yourself.

**Comment by Brokkonaut** [comment]
You can set the api-version to 1.13 - Older spigots ignore the version and newer spigots will not print a warning.

**Comment by Jikoo** [comment]
Yeah, I'm aware, but the plugin core is not compiled against 1.13.
