### ISSUE TITLE
1.14.2 PlayerInteractEvent with ShulkerBoxes

### ISSUE THREAD

**Issue by kakd** [lishid/OpenInv#103]
https://hasteb.in/owalijuf.rb

Using Paper-51

I now see I'm a couple versions behind. I'll assume you've already fixed this, and if that's the case, feel free to close it. I won't be able to personally test it out for about an hour.

**Comment by Jikoo** [comment]
Yeah, grab the correct version for your server. 1.14 = 4.0.0, 1.14.1 = 4.0.1, and 1.14.2 = 4.0.3
