### ISSUE TITLE
Allow using SilentChest to force loot generation

### ISSUE THREAD

**Issue by ironik42** [lishid/OpenInv#105]
I get this error every time I try to open a newly discovered and naturally generated chest. Cannot reproduce error in a vanilla world(no mods). Error occurs on latest release of Spigot [git-Spigot-01d0f04-b7fea42 (MC: 1.14.2)] and PaperMC [git-Paper-58 (MC: 1.14.2)]. The error is on screen only - nothing shows up in the log file. Adding a screenshot to show. *edit: removing the OpenInv.jar file fixes the issue but I would prefer to not have to delete it :) . 
![2019-05-31_23 57 01](https://user-images.githubusercontent.com/39577121/58745067-85226100-8400-11e9-94c6-d07b931d66e6.png)

**Comment by RoboMWM** [comment]
Well that makes sense. The loot generates when a player opens it. When "opening" silently you're bypassing this mechanism. Just exit silentchest mode if you wish for the chest to generate loot.

**Comment by Jikoo** [comment]
As Robo said, stop using SilentContainer to generate loot.

**Comment by ironik42** [comment]
This is still occurring after changing the config file. All three settings are set to false. 

![2019-06-01_13 17 49](https://user-images.githubusercontent.com/39577121/58753140-ee8d8880-846f-11e9-9146-f44bc36b4911.png)

As you can see from the screenshot, it still gives the same error message. No message in the server log either. 

Instead of outright dismissing this issue, how about doing some investigation into the issue instead of just saying 'change x in the config'. Unlike most people, I do my due diligence. I gave you very specific details about the error and on what platforms it occurs. The only thing I forgot to mention was the fact that I had already tried to change the config.yml settings, which as you can see, clearly did not work.

**Comment by ironik42** [comment]
This never happened before 1.14.x. I used silenchest all through 1.12 and 1.13 and never had an issue using silentchest on unlooted chests. Your fix is more of a band-aid than a solution.

**Comment by Jikoo** [comment]
What? There's no config change to make. Turn off SilentContainer for yourself in game via command. This has been a thing since we swapped to using spectate after the issues due to tile entity changes between Spigot and Paper.

**Comment by Jikoo** [comment]
It's possible to force loot generation, so I'll add this as a feature, but it's definitely not the intended usage of OpenInv. SilentContainer is for checking up on existing stuff in conjunction with vanish plugins and the like, not for having constantly enabled while exploring.

**Comment by RoboMWM** [comment]
If anything I prefer it to not generate loot, so I assume this would come as another config option.

**Comment by Jikoo** [comment]
I agree, honestly. I think a better approach to this "problem" is to take a leaf out of GP's book in encouraging responsible admin behavior and not have SilentContainer/AnyContainer persist across logins.

**Comment by Jikoo** [comment]
After some thought, leaving silentcontainer on constantly is not the intended purpose of the plugin, and I will not be adding loot generation. I have included a more clear error message in 3faf41ef. I will eventually likely make silentcontainer status not persist across sessions to encourage responsible admin behavior.
