### ISSUE TITLE
Automated building?

### ISSUE THREAD

**Issue by Fysac** [lishid/OpenInv#11]
At the moment, it's somewhat difficult for others to build Openinv, due to the large number of CraftBukkit versions it depends on. Perhaps we could introduce a system such as Gradle in order to make things easier?

**Comment by Fysac** [comment]
@MCTyler It looks like they compile it from the source repos here: https://hub.spigotmc.org/stash/projects/SPIGOT

**Comment by aikar** [comment]
It would be easier to drop support for old builds and only support latest.

Then others can manually compile Spigot/Bukkit themselves.

I ended up marking the other folders ignored to get it compiled and reference my latest .jar

**Comment by Fysac** [comment]
I agree.

**Comment by lishid** [comment]
Should probably drop the previous versions support at one point anyway. I did it for my other plugin a while back, but these days I barely have enough time to even check and reply on comments...

**Comment by ShadowRanger** [comment]
Support for previous versions have been dropped in the latest versions of OpenInv, closing issue.
