### ISSUE TITLE
Issue with some materials in /searchinv and /searchender

### ISSUE THREAD

**Issue by Kobe024** [lishid/OpenInv#112]
Hi, I am trying to use /seachinv and /seachender but for some materials like polished granite or birch logs etc... it keeps saying Unknown Item. I have tried minecraft:polished_granite, POLISHED_GRANITE, minecraft:stone and 1:2. None of them seem to work. It works for some items like arrow and chest but not for all of them. Is it maybe an issue with how material names where changed? Thanks in advance!

OpenInv - 4.0.6

Paper-196 for MC 1.14.4-R0.1-SNAPSHOT

Other Plugins: EssentialsX (Core, Protect, Anti-Build, Spawn, Chat, GeoIP), CoreProtect, Dynmap, MultiverseCore, Vault, WorldEdit, WorldGuard, WorldBorder

**Comment by Jikoo** [comment]
[4.0.7](https://github.com/lishid/OpenInv/releases/tag/4.0.7)

**Comment by Kobe024** [comment]
Thanks for the speedy reply and fix.
I tested it with the latest paper jar build-207 and it works fine now.
