### ISSUE TITLE
Unable to compile packages

### ISSUE THREAD

**Issue by naqibnadzir** [lishid/OpenInv#121]
Works fine for 1.18 but as soon as it reached 1.14, it says net.minecraft.server.v1_14_R1 does not exists. How do I import this using maven?

**Comment by naqibnadzir** [comment]
The reason I am doing this is to change the aliases for the silentchest command [sc] as it clashes with my other plugin and I would like this [sc] aliases to be removed. Thanks

**Comment by Jikoo** [comment]
Regarding compiling: you must have the correct versions of Spigot (not Spigot-API) installed in your local Maven repository to compile a particular NMS revision. BuildTools will automatically install for you when running, or you can manually install files using the process outlined in the readme.

>To compile, the relevant Craftbukkit/Spigot jars must be installed in your local repository using the install plugin.
Ex: `mvn install:install-file -Dpackaging=jar -Dfile=spigot-1.8-R0.1-SNAPSHOT.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.8-R0.1-SNAPSHOT`

Regarding your reason for compiling youself: you can use your [commands.yml](https://bukkit.gamepedia.com/Commands.yml) to enforce aliasing or you could edit the plugin.yml in the compiled jar to remove the alias.
