### ISSUE TITLE
Add ability to disable openinv player cache

### ISSUE THREAD

**Issue by rasputinea** [lishid/OpenInv#123]
hello, when I open a players inventory and close it then they login my plugin that converts inventory items on login doesn't work, probably because of the cache system is overwriting it. The cache is also causing other problems for me to the point where the option to disable it would be greatly appreciated. Thanks

**Comment by Jikoo** [comment]
Could you clarify what other problems you're having? Have you tried running your inventory checking code on a tick delay?

**Comment by Jikoo** [comment]
Removing the cache is not a solution, it would just make this edge case harder to spot - the same behavior would still be exhibited if the player's inventory was open when they logged in.
