### ISSUE TITLE
OpenInv.editinv permission not working

### ISSUE THREAD

**Issue by N0tMyFaultOG** [lishid/OpenInv#124]
I applied the permissions `OpenInv.editinv` and `OpenInv.openinv` and people can open the inventories fine tho they cannot edit them? 
Using OpenInv v4.0.8 on Paper 1.15.2 with LuckPerms v5.0.56

**Comment by Jikoo** [comment]
Cannot reproduce. This is an issue with your permissions configuration. You can use LuckPerm's `/permission check` to debug.

**Comment by ryantheleach** [comment]
I'm also getting this but on 1.16.2

![image](https://user-images.githubusercontent.com/141554/92328603-0a370400-f0a1-11ea-82f1-746053d166d6.png)

Able to open inventories, but not take items out.

![image](https://user-images.githubusercontent.com/141554/92328626-44080a80-f0a1-11ea-9ae7-e57625e81e00.png)

**Comment by Jikoo** [comment]
If you can reliably reproduce, please get me LuckPerms logs with verbose mode on.

**Comment by ryantheleach** [comment]
It's an invalid report sorry. When viewing the inventory in spectator mode, you cannot edit even with the permission.

So (if it's possible) it would be a feature request.
