### ISSUE TITLE
Opening wrong inventories

### ISSUE THREAD

**Issue by xtomyserrax** [lishid/OpenInv#125]
Hey, Im having this issue in which openinv is just opening wrong offline players inventories and it is happening with all players.

For example let me explain with the pictures im sending: I do /openinv serpient23 and it opens me the inventory or enderchest of geri33. geri33 in this case was online, but I can do it with other offline players and it opens the inventory of another different offline player. This happens sometimes and when it does, it happens with all offline inventories

Here you have screenshots showing you what Im doing, and also a /seen showing that player has played.  https://imgur.com/a/zzRDR9U

Im using latest spigot version and latest OpenInv version (4.0.8)

Do you have an idea of how I can fix it or is it a plugin bug? Let me know if you need more information. Thanks!

**Comment by RoboMWM** [comment]
What's your server configuration? Online mode? Bungee?

**Comment by xtomyserrax** [comment]
Heyy server is with online mode set to false and yes its using BungeeCord. What do you mean with server configuration? Or it was that info?

**Comment by Jikoo** [comment]
The contents of spigot.yml would be useful, along with the entry for those users from your usercache.json - the way OpenInv checks players by name goes online exact, offline exact using Spigot's cache, and then by comparing every offline player's name to the searched text. The only point of failure I can see being OpenInv's fault is the string metric not correctly comparing the names.

**Comment by xtomyserrax** [comment]
Basicly the behaviour works like this: OpenInv works perfectly fine in some servers, with the exception of one in which it is failing every time despite server reloads. It is just giving wrong inventories to all offline players, not just one, but all, it fails with every single name you give. But this doesnt happen in all servers, so Im not sure to tell you what causes this to happen.

Will let you know if I can send you those files or if I notice something else about this behaviour

**Comment by Jikoo** [comment]
Sounds very much like the user cache is returning incorrect UUIDs, but hard to be sure without the files I mentioned. Do partial matches still pull the correct user, I.E. if geri33's inventory opens properly and you try to open geri3, will it still open geri33?

**Comment by xtomyserrax** [comment]
Will send you the files as soon as I can! 

Look at this new video, server just restarted, so now every offline player inventory I try to open, instead of opening the one I asked, it is opening inventories from online players. https://imgur.com/a/hXihUw4

**Comment by Jikoo** [comment]
In that case, it's probably your user cache being messed up. OpenInv depends on the server for everything except matching-based player selection. If the user cache is messed up, it'll fail before hitting username matching. You can try other inexact names to force it to search to see if that's the case.

**Comment by xtomyserrax** [comment]
Hmm you mean about this? https://imgur.com/a/A40MGwv and https://imgur.com/a/kBhBx5Y

The weird thing is that this is not returning the player right? I mean the majority of times it should work?  player = Bukkit.getServer().getOfflinePlayer(name);

So the cache then is doing weird things I guess? Because it starts working bad when server restarts, and only works with offline players who played after the server restarted

**Comment by Jikoo** [comment]
Yeah, that very much seems like an issue with the server, surprised you're not seeing any issues in other plugins. Please try deleting and reinstalling OpenInv and the server software. If issues persist, please delete usercache.json.

**Comment by Jikoo** [comment]
Closing due to lack of response, seems to be an issue with server setup/software.
