### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by crckdns** [lishid/OpenInv#126]
As there is no prebuild release, I've tried to build it myself.
It fails, as the path for 1.14 is wrong it seems (I tried to build for every version as I have no clue how to build for 1.15.x paper ^^)

`[INFO] ------------------< com.lishid:openinvadapter1_14_R1 >------------------
[INFO] Building OpenInvAdapter1_14_R1 4.0.9-SNAPSHOT                      [6/8]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot/1.14.3-R0.1-SNAPSHOT/maven-metadata.xml
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot/1.14.3-R0.1-SNAPSHOT/spigot-1.14.3-R0.1-SNAPSHOT.pom
[WARNING] The POM for org.spigotmc:spigot:jar:1.14.3-R0.1-SNAPSHOT is missing, no dependency information available
Downloading from spigot-repo: https://hub.spigotmc.org/nexus/content/groups/public/org/spigotmc/spigot/1.14.3-R0.1-SNAPSHOT/spigot-1.14.3-R0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenInvParent 4.0.9-SNAPSHOT:
[INFO]
[INFO] OpenInvParent ...................................... SUCCESS [  8.019 s]
[INFO] OpenInvAPI ......................................... SUCCESS [ 13.550 s]
[INFO] OpenInvPlugin ...................................... SUCCESS [  3.662 s]
[INFO] OpenInvInternal .................................... SUCCESS [  0.027 s]
[INFO] OpenInvAdapter1_8_R3 ............................... SUCCESS [  4.176 s]
[INFO] OpenInvAdapter1_14_R1 .............................. FAILURE [  5.468 s]
[INFO] OpenInvAdapter1_15_R1 .............................. SKIPPED
[INFO] OpenInvAssembly .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.083 s
[INFO] Finished at: 2020-04-10T22:06:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openinvadapter1_14_R1: Could not resolve dependencies for project com.lishid:openinvadapter1_14_R1:jar:4.0.9-SNAPSHOT: Could not find artifact org.spigotmc:spigot:jar:1.14.3-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/) -> [Help 1]`

**Comment by RoboMWM** [comment]
run buildtools to get the spigot jar in your local maven repo.

**Comment by Jikoo** [comment]
What Robo said. The readme also details manual installation [here](https://github.com/lishid/OpenInv#for-developers) in case you are using pre-BuildTools artifacts.

As far as releases go, I believe I had a couple more things I wanted to get done before pushing a build, as this will end up being a minor version bump.
