### ISSUE TITLE
Chest Bug

### ISSUE THREAD

**Issue by Mopar74** [lishid/OpenInv#127]
Having an issue were admins cannot break some chests while plugin is installed on server, it just opens the chest.

**Comment by Jikoo** [comment]
OpenInv does not open containers on actions other than non-sneaking right click. [PlayerListener.java#L57](https://github.com/lishid/OpenInv/blob/7210f9153ed3ec9cf66474f71737fab67b7eec5f/plugin/src/main/java/com/lishid/openinv/listeners/PlayerListener.java#L57)
