### ISSUE TITLE
/openender shows %Player in the title instead of the actual player name

### ISSUE THREAD

**Issue by Robby-** [lishid/OpenInv#130]
When using `/openender` on myself or anyone else it will show the title as `%Player's Ender Chest`.

Looking inside `en_us.yml` I saw that in the `container` string for `player` the token was different from the one in `enderchest`, so I changed `%Player` to `%player%` (thus, lower-casing the p and adding an extra %) and that fixed the issue. It now shows the player's name correctly.

Versions in use are:
OpenInv 4.1.0
Spigot 1.15.2 - CraftBukkit version git-Spigot-2040c4c-893ad93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Robby-** [comment]
.....aaaaaaand I just noticed in the commits log that this was fixed almost right after 4.1.0 was released. Welp.

**Comment by Jikoo** [comment]
Yeah, I should probably draft a release for that soon.
