### ISSUE TITLE
OpenInv Latest 1.13 version bug

### ISSUE THREAD

**Issue by p1u70n** [lishid/OpenInv#132]
# Java version not supported
I have the plugin under his latest release for Minecraft 1.13 with a correct Minecraft server configuration but the plugin doesn't work with Java 11.0.6. Please is it possible to make the plugin compatible with Java 11.0.6?
Thanks a lot,
Pluton.

**Comment by Jikoo** [comment]
1.13 is no longer supported. OpenInv only supports the latest 2 MC versions and 1.8.
For 1.13, use [4.0.7](https://github.com/lishid/OpenInv/releases/tag/4.0.7)

**Comment by p1u70n** [comment]
> 1.13 is no longer supported. OpenInv only supports the latest 2 MC versions and 1.8.
> For 1.13, use [4.0.7](https://github.com/lishid/OpenInv/releases/tag/4.0.7)

Ok thanks, but why abort the 1.13 mc version for the plugin?
