### ISSUE TITLE
ability to disable player cache

### ISSUE THREAD

**Issue by rasputinea** [lishid/OpenInv#133]
hello, the cache system for openinv is causing me more problems when it creates, seems to be interfering with several of the plugins I wrote that manipulate inventories. Players ender chests being reverted, datafixers not working, etc, even on tick delay every month something new comes up. Some way to disable this and prevent all the pain this has caused so far would be great.

**Comment by Jikoo** [comment]
You completely ignored my request for more information in your last issue. Provide an example of something that does not function correctly so I can help you fix it. If you won't work with me, I can't help you.

It is not possible to "disable" the cache. Even without a cache OpenInv will still modify players who come online as necessary. OpenInv now operates on LOWEST priority to modify players as soon as they are available. Please either adjust down your listener priority or softdepend on OpenInv so it can register its listeners first and guarantee it grabs the player before you.
