### ISSUE TITLE
Creates en_GB.yml missing translation

### ISSUE THREAD

**Issue by OskyEdz** [lishid/OpenInv#134]
I noticed that there was a % missing in %player% on enderchests. Fixed that. (I saw your commit too.)

But did you get that even though I have it on en_US it looks in en_GB for translations? It works ingame correctly, but there is that LanguageManager message in console every time someone use the commands.

I worked around by copy paste en_US to en_GB...

**Comment by Jikoo** [comment]
The system will (as of next release) actually properly save en_gb.yml for your editing pleasure. It always falls through to en_us. OpenInv now supports player locale, not just server locale.
