### ISSUE TITLE
/openender or /openinv will open latest user instead of self

### ISSUE THREAD

**Issue by OskyEdz** [lishid/OpenInv#135]
If I open another players inventory or enderchest. With /openinv <player>
Then open for myself with "/openinv" I will get that same players inventory again instead of my own inventory.

It's a weird thing, I would have it open my inventory always, with the single command.

**Comment by Jikoo** [comment]
That's an intended feature, saves re-typing names. Opening your own inventory isn't really recommended in the first place.
