### ISSUE TITLE
Inventory#getLocation causes NPE when called on silent ender chest

### ISSUE THREAD

**Issue by Jikoo** [lishid/OpenInv#143]
Specifically a 1.16 problem, may be Spigot's problem and not ours - last I recall silent ender chest is purely API-based.

**Comment by RoboMWM** [comment]
I think I've encountered this when attempting getLocation on an ender chest (or fake ender chest inventory?) as well. Let me see what I did about this...

**Comment by RoboMWM** [comment]
This isn't what I recall, but search results gave me this: https://github.com/MLG-Fortress/PrettySimpleShop/pull/7

**Comment by Jikoo** [comment]
Silent ender chest [is API-only](https://github.com/lishid/OpenInv/blob/master/internal/v1_16_R1/src/main/java/com/lishid/openinv/internal/v1_16_R1/AnySilentContainer.java#L173-L178) like I thought. Going to leave this open until I make time to double check it but it should be simple to reproduce.
```Java
InventoryView view = player.openInventory(bukkitPlayer.getEnderChest())
if (view != null) {
    view.getTopInventory().getLocation();
}
```

**Comment by Jikoo** [comment]
Looks like this was [fixed](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a339310c48548f0f82f923ff3f5fe2cdc7a8e8ba), kinda forgot about reporting it. Whoops.
