### ISSUE TITLE
compatibility request for PremiumVanish

### ISSUE THREAD

**Issue by mrcoffee1026** [lishid/OpenInv#148]
Premium Vanish already provides several of this plugins features... and this plugin overrides those: particularly the "silent container" feature.  In Premium vanish this is automatically enabled for staff accessing chests while hidden, which is appropriate, where as this plugin disables the animation always and forever, which is not.  I have tried some variations with the permissions for openinv.silent and openinv.silent.default such as providing the permission only contextually while the staff person is hidden... but this doesn't actually work.  The user must ALSO type the command /silentcontainer to enable it... and then when they come out of v of course they can't disable it again, so it just stays on forever after that.

There's also a glitch that happens if you have the permission removed while in vanish and open a chest, the animation is not displayed but the lid displays as open for you anyway, and stays that way until you reconnect to the server, there does not seem to be any other method or resetting how the lid looks to you.   If possible I would like the silent container thing to just be optional in case another plugin is already doing this.  I do - however - really like the possibility of opening chests with blocks on them, that is very nice.

**Comment by mrcoffee1026** [comment]
Should have also stated that if I have no permission to use the silent container feature, this causes the animations and sounds to display to everyone while I'm in vanish - disabling the feature that vanish provides - which is why this is so undesirable.

**Comment by Jikoo** [comment]
AnyContainer is only compatible with OpenInv's SilentContainer. You can use a vanish plugin that will run additional commands while enabling/disabling vanish, that is specifically why the explicit setting parameters (`/sc on|off`) are available. If you do not want to use OpenInv's SilentContainer, you can use the same technique to automatically disable AnyContainer while in vanish.

**Comment by mrcoffee1026** [comment]
Yes and Premium Vanish actually does have the ability to add that command on entering and leaving the mode.  Unfortunately, that command can't actually be run from the console so that is no benefit at all. In order for it to be functional you'd need to be able to pass an argument so that something like /silentcontainer {player} off could be used.

**Comment by Jikoo** [comment]
Based on what you said, running it as a player would work fine for turning off AnyContainer while in vanish. I know other vanish plugins can be configured to be compatible with OpenInv's system, if yours can't it sounds like you should seek out a better plugin. I believe the user who requested the explicit state setting commands was using SuperVanish.

Either way, I am not going down the rabbit hole of support dozens of vanish plugins. You can ask your vanish plugin's developer to support OpenInv if you can't figure out a way to manage with their existing tools, OpenInv offers an API that can be used to toggle container settings.

**Comment by mrcoffee1026** [comment]
Yeah nevermind, they have a workaround for this command's lack of arguments, thanks.

**Comment by mrcoffee1026** [comment]
also, thanks for the help :D

**Comment by Jikoo** [comment]
No problem. Your other proposed solution, a player parameter, would probably break compatibility with area-based perm nodes. Unfortunate edge cases. If you do still have issues and your vanish plugin can't help we can try to explore options in that regard, but it would probably require a significant amount of plugin retooling or fiddling.
