### ISSUE TITLE
1.16.2

### ISSUE THREAD

**Issue by Matrix1017** [lishid/OpenInv#149]
The plugin only works in the versions before 1.16. If fixed it would be greatly appreciated

**Comment by Jikoo** [comment]
Use the snapshot I released a couple days ago.

**Comment by Matrix1017** [comment]
Where would i be able to find this, I'm playing on this free hosting server *Minehut.com* and is it just the owners of Minehut that needs to update the plugin? or would i have to do it myself

**Comment by Jikoo** [comment]
The snapshot is [tagged here](https://github.com/lishid/OpenInv/releases/tag/4.1.4-SNAPSHOT). If you can't figure out how to update plugins on your server you need to contact your host - I have no idea what they offer. On a normal system you manage, you'd follow the same procedure as updating any other plugin - stop the server, delete the old version, and install the new version.
