### ISSUE TITLE
1.16.1 server crash after cmd "/searchender shulker_box 90"

### ISSUE THREAD

**Issue by donvdp** [lishid/OpenInv#153]
A moderator on my server executed the "/searchender shulker_box 90" command that caused my server so crash and reboot.
Any ideas on how to fix this? and is there a workarround for the time being? I hate for my server to crash due to faulty coding.

pastebin is down. so i,ve included the dump into this text file:
https://we.tl/t-gHg0BC84zO

Running
- Paper-136
- OpenInv v4.1.4

**Comment by Jikoo** [comment]
Yeah, don't search a 90 chunk radius. There's a reason it defaults to 5.
