### ISSUE TITLE
Allow spectators to edit chest/players/enderchests with editinv permission

### ISSUE THREAD

**Issue by ryantheleach** [lishid/OpenInv#155]
Possibly locked behind an option or additional permission, incase this screws someones usecase.

**Comment by Jikoo** [comment]
Are spectators actually allowed to interact with items in containers? I don't really want to take on reimplementing the entirety of inventory handling (assuming the client sends the information at all), but if it's just a case of un-cancelling the event while a user with the correct permissions is in spectate that should be doable.
