### ISSUE TITLE
Server Version not supported.

### ISSUE THREAD

**Issue by QuivMC** [lishid/OpenInv#156]
Hi, I tried to download the latest version, but it told me to check this website for an update. Please help
Server version: 1.12.2
Version said in chat: v1_12_R1
![image](https://user-images.githubusercontent.com/71019310/93346886-09535e80-f867-11ea-9f12-42e8c934d048.png)

**Comment by RoboMWM** [comment]
R1 is for revision 1 which I believe 1.12.2 is. The current version of OpenInv does not support 1.12.2. You will need to use an older version.

**Comment by Jikoo** [comment]
OpenInv only supports the latest 2 major + latest 2 minor versions and 1.8.8. To use OpenInv on 1.12 you will need to use an older version. The last version supporting 1.12 was [4.0.0](https://github.com/lishid/OpenInv/releases/tag/4.0.0).

**Comment by Jikoo** [comment]
Should also note, you will need to use the file OpenInv-legacy, as it contains support for all outdated versions - the main 4.0.0 build only supported 1.14, 1.13, and 1.8
