### ISSUE TITLE
Multiverse Inventories support.

### ISSUE THREAD

**Issue by IIPedro** [lishid/OpenInv#158]
[Multiverse Inventories](https://dev.bukkit.org/projects/multiverse-inventories) is a plugin that makes it possible to create different worlds within a single minecraft server. It is very useful to small server owners. I suggest making OpenInv compatible with Multiverse Inventories. It would be of immense help. Thank you, and have a nice day!

**Comment by Jikoo** [comment]
Duplicate of #122
