### ISSUE TITLE
Dont support Paper 1.12.2

### ISSUE THREAD

**Issue by PerchunPak** [lishid/OpenInv#159]
![image](https://user-images.githubusercontent.com/68118654/95223668-86d51380-0802-11eb-9bed-a8ecbf21d68c.png)
OpenInv write that dont support Paper 1.12.2

I use last version 4.1.4

**Comment by Jikoo** [comment]
You must use an older version for outdated servers. I believe 4.0.0 was the last version supporting 1.12.
