### ISSUE TITLE
Not working on latest version of Paper.

### ISSUE THREAD

**Issue by brofin** [lishid/OpenInv#161]
Trying to execute any openinv command results in this message:
"Your version of CraftBukkit (v1_16_R2) is not supported. If this version is a recent release, check for an update."

Though I noticed others have commented and said it works fine for them in 1.16.3 so not sure what could be going on.

**Comment by Jikoo** [comment]
Sounds like you're using an outdated version. Update OpenInv.

**Comment by brofin** [comment]
Sorry about that. I thought I had updated the plugin recently but I was mistaken.

Thanks!
-Chris

________________________________
