### ISSUE TITLE
Chests stuck open when /op is active

### ISSUE THREAD

**Issue by brofin** [lishid/OpenInv#162]
When /op is active, any chests I open have their animation stuck in the open state. Otherwise does not effect the actual use of the chests.
Confirmed that this issue goes away when OpenInv is disabled.
Latest 1.16.3 build of Paper. Latest version of OpenInv.

**Comment by Jikoo** [comment]
Unable to reproduce using OpenInv 4.1.4 on Paper 248.
* When reporting issues, "latest" is never a valid version.
* `/silentcontainer` or `/anycontainer`?
* Other plugins?

**Comment by brofin** [comment]
Paper 247,  OpenInv 4.1.4

/anycontainer didn't seem to have any effect.
Even with OP I didn't have access to /silentcontainer so I had to give myself permission for that. Then after entering the command to set Silent Container to false the problem with the chests staying open went away.

I've attatched a screenshot showing the other plugins I have enabled in case you'd like to see.

Thank you!

[cid:0880d4bb-788a-43e4-b76c-d23a3313f3b1]
________________________________

**Comment by Jikoo** [comment]
Looks like the attachment from email screwed up. Either way, I cannot reproduce with only OpenInv installed. Chests always close properly, even when opened while another user has them open.

To track down the incompatibility, try first with only OpenInv, then half your plugins at a time. Vanish plugins are likely culprits.

> Even with OP I didn't have access to /silentcontainer so I had to give myself permission for that.

That's a problem with your permissions setup, works fine for me with only OpenInv installed and op status.

**Comment by Jikoo** [comment]
I guess technically an edge case for this would be if the user somehow turns on `/silentcontainer` after opening an inventory, at which point it would be stuck open until they reversed the process. That said, it's impossible for that to occur without "foul play" i.e. another plugin modifying the user's state or bypassing normal open.
