### ISSUE TITLE
[OpenInv] [LanguageManager] Missing translations from it_it.yml: 

### ISSUE THREAD

**Issue by Fargus5** [lishid/OpenInv#164]
[18:07:16] [Server thread/INFO]: Fargus issued server command: /oi Fargus
--
1548 | [18:07:16] [Server thread/INFO]: [OpenInv] [LanguageManager] Missing translations from it_it.yml: messages.error.consoleUnsupported, messages.error.lootNotGenerated, messages.error.invalidMaterial, messages.error.invalidNumber, messages.error.invalidPlayer, messages.error.permissionOpenSelf, messages.error.permissionEnderAll, messages.error.permissionExempt, messages.error.permissionCrossWorld, messages.error.permissionPlayerOnline, messages.error.permissionPlayerOffline, messages.error.commandException, messages.info.containerBlocked, messages.info.containerBlockedSilent, messages.info.containerSilent, messages.info.settingState, messages.info.player.noMatches, messages.info.player.matches, messages.info.container.noMatches, messages.info.container.matches, messages.info.true, messages.info.false, container.player, container.enderchest

I never selected Italian language... so I don't understand

**Comment by Jikoo** [comment]
Your client is set to Italian so OpenInv attempts to load Italian translations for you. Italian does not exist, so it will fall through to English. You will only see this warning once per language per server start.

PRs for additional translations are welcome, files go [here](https://github.com/lishid/OpenInv/tree/master/plugin/src/main/resources).
