### ISSUE TITLE
it doesnt work on 1.9 for me 

### ISSUE THREAD

**Issue by suys69** [lishid/OpenInv#166]
![image](https://user-images.githubusercontent.com/68744295/98293494-16fba980-1fb7-11eb-8334-302e49e34435.png)

**Comment by Jikoo** [comment]
You must use [4.0.0](https://github.com/lishid/OpenInv/releases/tag/4.0.0) for outdated versions. Be sure to download OpenInv-legacy.

**Comment by suys69** [comment]
Thanks
