### ISSUE TITLE
Unable to edit inventory

### ISSUE THREAD

**Issue by temoya1** [lishid/OpenInv#168]
I can open the player's inventory, but you cannot move items.
The ender chest works fine.
No error is displayed on the console.
The server version is Spigot 1.16.4 and the permissions are "openinv. *".

The text may be poor because it is translated and written. sorry

**Comment by Jikoo** [comment]
OpenInv's permissions start with OpenInv, not openinv. Some permissions systems are case-sensitive.

Please consider using LuckPerm's verbose mode, which will allow you to see exactly which permissions are in what state when checked.

**Comment by temoya1** [comment]
[image: image.png]

I examined the logs using the "/lp vorbose on Openinv" command, but could
not determine the cause.

>

**Comment by temoya1** [comment]
![image](https://user-images.githubusercontent.com/74515177/99235692-82f0d400-2839-11eb-877b-704d2e65df99.png)
