### ISSUE TITLE
Introducing barrier blocks for the inventory slots that are not part of the inventory

### ISSUE THREAD

**Issue by baailey** [lishid/OpenInv#172]
Implementing this feature will support a more user-friendly interface for all. My thoughts are that the barriers will go [here](https://i.imgur.com/5LKMhyc.png), though if you have a different item in mind, it's your decision. 

Currently if an Admin, Mod etc. try to place an item in those slots, the item will just be dropped in front of you. For those who may not be aware of this, it could result in a possibly expensive item being dropped on accident when they wanted to place it in another staff members inventory. 

I hope to see this introduced!

**Comment by Aurelien30000** [comment]
On a hand I agree, however, this is a feature of the plugin:

_Drop items as the other player (by putting it in the unused slots in the bottom right)_

You should wait for the opinion of maintainers ;)

**Comment by Jikoo** [comment]
I do plan to add this eventually, but it will need to be done with #150 and some internal changes to allow translations to be obtained for barrier info.

Medium complexity, low priority. <sub>See you all in 2024 when I get around to this. <sub>Just kidding. _I hope_.</sub></sub>

**Comment by RoboMWM** [comment]
Github supports sub/superscript? ^test

**Comment by Jikoo** [comment]
GitHub supports some HTML, good ol' \<sub\> tags.

**Comment by Jikoo** [comment]
The drop slot is now a client-side dropper renamed to the translation key "key.drop" which is  "Drop Selected Item" in en_us. Other unused slots are a white stained glass pane with no tooltip. In the future this will be configurable.

/e: Also, wow, 2024, just as predicted. I know myself too well.
