### ISSUE TITLE
Chest stay open

### ISSUE THREAD

**Issue by CubBossa** [lishid/OpenInv#174]
All chests that were opened stay open on paper 1.16.5 (457). When I disable the plugin and destroy and place an open shulkerbox the new placed shulkerbox is not open anymore

**Comment by Jikoo** [comment]
Cannot reproduce running paper 465.

Frankly, not sure what you're trying to describe here. It sounds like you're having problems with chests staying open, but then you specifically reference placing an "open" shulker box, i.e. it is already opened at time of placement.

Please provide reproduction steps and a clearer description of the problem.
