### ISSUE TITLE
OpenInv blocks custom tile entity names

### ISSUE THREAD

**Issue by leasoncre** [lishid/OpenInv#175]
Open Inv blocks tile-entity CustomName edits from SHOWING to the client until the server restarted (or the plugin is unloaded - in test)

to reproduce:
Paper 1.16.5-457 | Open Inv 4.1.5 [Authors: lishid, Jikoo and ShadowRanger] | (Playing as OP)
1. place an un-nammed chest or double-chest
2. /data modify block <x> <y> <z> CustomName set value '{"text":"Custom Name here"}'
3. open chest, display name does not change
4. /data get block <x> <y> <z> 
5. Custom name field IS listed in tags!
6.  restart server, no change
7. remove or unload OpenInv. customName shows as expected

>this appears to only be a problem for OPs/(maybe Admins with w/e specific Openinv permissions or function may be related) Standard players don't have this issue, and see the custom name
-tested on LARGE_CHEST, issue does not appear on shullkers

**Comment by Jikoo** [comment]
Try without silent/anycontainer enabled. In general you should not just be leaving those modes enabled 24/7 - they're admin tools, not normal game mechanics.

**Comment by leasoncre** [comment]
for some reason i had `openinv.silent FALSE` set on my player in LuckPerms, WITH it enabled.... must have done derped ages ago and never looked into it.
+Removing that node and turning it off fixed the issue
thank you

**Comment by Jikoo** [comment]
I'm going to leave this open because it's certainly possible to fix, but I probably won't get to it for a good while because it's cosmetic.

Actually, shoulda labelled it a bug, my bad.

**Comment by leasoncre** [comment]
oops closed wrong ticket, both referenced the same silentchest thing

**Comment by leasoncre** [comment]
Tested w/o silent chest enabled. same result.
>disabled anycontainer, Name appears!, re-enabled anycontainer, same issue.

why did i have this enabled from ages ago.. >_>
