### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by Aurelien30000** [lishid/OpenInv#177]
Hey!

Using a file top import OpenInv from maven isn't really reliable and I wondered if you could consider using github packages as a maven repo for this project.

Thanks ;)

**Comment by Jikoo** [comment]
Builds are available via [JitPack](https://jitpack.io/).
```XML
    <dependency>
      <groupId>com.github.lishid.OpenInv</groupId>
      <artifactId>api</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
```
