### ISSUE TITLE
double hand animation

### ISSUE THREAD

**Issue by seema84** [lishid/OpenInv#183]
Hey, i am not sure if it is intentional, when anycontainer or anychest is active, two animations are displayed with the right hand.

Paper-470 (MC: 1.16.5)
OpenInv v4.1.5

the funny thing is that it only happens together with optifine

**Comment by Jikoo** [comment]
Not something that can be addressed by OpenInv, all we do is cancel container interaction when necessary.

**Comment by seema84** [comment]
all right thanks, was not quite sure
