### ISSUE TITLE
/searchinv doesn't include armor or offhand slots

### ISSUE THREAD

**Issue by trqzh** [lishid/OpenInv#186]
I was just trying to see if anyone had a totem on my server but it didn't show my totem even though it was in my offhand, then I noticed it wouldn't show my netherite armour either.

**Comment by Jikoo** [comment]
Please reopen over at https://github.com/Jikoo/OpenInv

Should note, I am actively rewriting the search function so that it's a lot more flexible and (in the case of `/searchcontainer`) a lot less dangerous.
