### ISSUE TITLE
Log item manipulation

### ISSUE THREAD

**Issue by Bloodlex** [lishid/OpenInv#187]
Hello,

I think it would be nice to have a feature, to log everything that happened in someone else's inventory. It would allow me to perform better supervision over my server stuff.

Best regards,
Bloodlex

**Comment by Jikoo** [comment]
Please reopen over at https://github.com/Jikoo/OpenInv

If you could include more details about what you'd hope to see in logs, how you'd want them to be accessible, etc. that could also be useful.
