### ISSUE TITLE
Custom EnderChest support

### ISSUE THREAD

**Issue by ItzRonaldMLG** [lishid/OpenInv#189]
Hello,

Any change you could support Custom EnderChest plugin? (https://www.spigotmc.org/resources/custom-enderchest.8868/)?
Now if i do /openender it opens the enderchest from vanilla, also the plugin Quickshop that uses openinv (https://www.spigotmc.org/resources/quickshop-reremake-1-16-ready-multi-currency.62575/)
I cant use this feature when having Custom EnderChest plugin on the server sadly.

**Comment by Jikoo** [comment]
New issues belong over at [Jikoo/OpenInv](https://github.com/Jikoo/OpenInv).

If you want commands from a plugin to override commands added by another, you can use Bukkit's [commands.yml feature](https://bukkit.fandom.com/wiki/Commands.yml) to assign openender -> customenderchest:openender. Anything overriding inventory behavior needs to implement offline access itself, it's not feasibly possible to add and maintain support for every multi-inventory/inventory modification plugin.
