### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by Mrredstone5230** [lishid/OpenInv#190]
Hey, would it be possible to add 1.17 support ?

**Comment by Jikoo** [comment]
1.17 support is only available for people willing to look at releases.

**Comment by Mrredstone5230** [comment]
I don't think I understand your answer. When I try to use the plugin in 1.17, it shows a message that the server isn't compatible with the plugin. Also, I didn't see any 1.17 release, either on bukkit.org or on GitHub.
