### ISSUE TITLE
is not loading 

### ISSUE THREAD

**Issue by sonicwolfsdutch** [lishid/OpenInv#24]
getting error message 

http://pastebin.com/NdS1GgCB im using 1.8.7 Buildtools #38

**Comment by lishid** [comment]
You might want to upgrade your java version?

**Comment by sonicwolfsdutch** [comment]
the new java 7 v80 or java 8 v45?

**Comment by sonicwolfsdutch** [comment]
well java 7 v80 dint work http://pastebin.com/vDFY4jFE

**Comment by ShadowRanger** [comment]
Please recreate a new issue if you are still experiencing this problem.
