### ISSUE TITLE
1.8 compatibility

### ISSUE THREAD

**Issue by JohOply** [lishid/OpenInv#46]
Hi guys,

Comment section and PM don't work, so i create a ticket to request an update with the compatibility in 1.8 :)

> MegaNarwhal
> May 11, 2016 at 00:54 - 0 likes Like
> 
> @JohOply: Go
> 
> http://dev.bukkit.org/bukkit-plugins/openinv/files/66-open-inv-2-3-4/
> 
> Or use OpenInv 2.3.0 if you need support for 1.8.0.

Currently i use it (2.3.0), but there is a recently fixed bug about enderchest, i thought it was possible to have latest version of plugin compatible with 1.8 :)

Thank you for reading

**Comment by Phoenix616** [comment]
For now you could use my [fork](https://github.com/Phoenix616/OpenInv) which supports all of the versions up to 1.9.

**Comment by Jikoo** [comment]
OpenInv no longer offers backwards compatibility. If you want an updated version for 1.8, check out [my fork](https://github.com/Jikoo/OpenInv) or [Phoenix616's fork](https://github.com/Phoenix616/OpenInv). I believe @Phoenix616's lacks a couple dupe fixes, but I could be wrong (tagging you in case, #40 and #49 both probably affect you)

**Comment by Jikoo** [comment]
Released [3.0.0](https://github.com/lishid/OpenInv/releases/tag/3.0.0) with backwards compatibility

**Comment by Phoenix616** [comment]
Wow, this is awesome! Good job on bringing backwards compatibility back, now I can retire my fork! :D

**Comment by JohOply** [comment]
Thank you :)
