### ISSUE TITLE
Since you are able to get into the .dat file when players are offline, while your there, could you allow us to change the position of a player?

### ISSUE THREAD

**Issue by Razorskills** [lishid/OpenInv#5]
I am interested in being able to change the position of an offline player in game. I know this is an inventory plugin, but you are already in the .dat file and the command could be /openinv position 'name' 0 64 0  (Or maybe just 'here')

This would be useful for a couple times i wiped the players .dat file to fix their location in the server. So in a way it relates to the inventory not getting wiped.. haha
(that was after I found a .dat file editor and was able to upload the file to my pc, then fix it, then reupload to the server. A long process to change 3 numbers)

It might be best to set it only to be able to be used if the player is offline, then it cannot mess with current online players.

But I do think it would be a god feature!

**Comment by ShadowRanger** [comment]
OpenInv is specifically for working with inventories, not player locations. Unfortunately I don't think this will be added to the plugin, however, I'm sure it could be done with a separate plugin.
