### ISSUE TITLE
Sideways Shulker Box: "You are opening a blocked container"

### ISSUE THREAD

**Issue by SimonOrJ** [lishid/OpenInv#55]
Shulker boxes will always trigger "opening blocked container" message when a block is on top of the box, no matter what orientation the shulker box was placed..  It does not display the message when the shulker is actually blocked.

**Comment by Jikoo** [comment]
[AnySilentContainer#120](https://github.com/lishid/OpenInv/blob/master/internal/v1_11_R1/src/main/java/com/lishid/openinv/internal/v1_11_R1/AnySilentContainer.java#L120)
All shulker boxes report themselves as being the default orientation. Not sure what can be done about this, that's ripped directly from the source.
