### ISSUE TITLE
Disable drop item in 1 and 2 slots

### ISSUE THREAD

**Issue by DardBrinza** [lishid/OpenInv#57]
I use customJoinItems and openinv, i don't know why, but this plugin blocked drop item in 1 and 2 slots in inventory. Latest build paper spigot 1.8.8, latest version openinv and customjoinitems, in console no errors.

**Comment by Jikoo** [comment]
OpenInv does not handle the PlayerDropItemEvent at all. Sounds like CustomJoinItems thinks you have 2 un-droppable items. Check your CustomJoinItems config.

**Comment by DardBrinza** [comment]
No, if i delete openinv, all works fine, my customjoinitems config don't use function to disable drop

**Comment by Jikoo** [comment]
OpenInv does not disable dropping functionality unless you do not have permission to modify an open OpenInv inventory implementation, an ISpecialPlayerInventory or an ISpecialEnderChest. In that case, you would not be able to modify any slots at all. Relevant listener [here](https://github.com/lishid/OpenInv/blob/master/plugin/plugin-core/src/main/java/com/lishid/openinv/listeners/InventoryClickListener.java#L37-L47).

CustomJoinItems' movement blocking will also perform drop prevention.
