### ISSUE TITLE
/silent protects the chest when enabled

### ISSUE THREAD

**Issue by smmmadden** [lishid/OpenInv#67]
I have been trying to figure out why I couldn't use my Axe to break a chest and realized I open them silently since I open chests a lot and didn't want to hear the sounds.  So after using /silent I can open any chest silently and it works fine.  

However, with Minecraft Client 1.12, BungeeCord Server 1.12 & Spigot Server 1.12 with OpenInv v3.2.1, the /silent command is also protecting the chest from breakage.  Turn silent off and like magic I can break the chest again.  I could break the chest with just an empty hand, but no axe, pickaxe, sword or other tool can break the chest.  Holding down the left mouse to break doesn't send the repeating event to enable breaking it.  I did not have this issue in 1.11.2, so this is a regression issue for 1.12.

**Comment by Jikoo** [comment]
OpenInv [only handles right clicks](https://github.com/lishid/OpenInv/blob/master/plugin/plugin-core/src/main/java/com/lishid/openinv/listeners/PlayerListener.java#L58), it's likely a conflict with another plugin. Can you reproduce it with only OpenInv installed?

**Comment by smmmadden** [comment]
checking it out on my testing server, just need to back everything up first.  Will let you know shortly.

**Comment by smmmadden** [comment]
Confirmed - removing all the other plugins I am able to break the chest in /silent mode.  Now onward to finding the culprit that's overriding this behavior. :-)

**Comment by Jikoo** [comment]
I assume it's a protection plugin - interaction is cancelled, making it appear that the chest is unopenable. "Can't open chest, can't destroy chest" sort of deal.

**Comment by Jikoo** [comment]
I'm going to leave this open for now in case you do track down the culprit, might be something I can fix on OpenInv's end, but it's somewhat unlikely.

**Comment by smmmadden** [comment]
I just found it.  It's the QuickShop Plugin.  Took a while going through 45 of them, disabling/enabling, etc.  But disabling QS, I can break the block.  Enabling QS, I can't break the block.  I'll let that developer know that their setting for sneak-to-create: false and sneak-to-trade: false does allow the player to create a chest shop by left clicking.  But it also disables breaking using any block with the left click unless its an empty hand. :-)

**Comment by Jikoo** [comment]
All right, thanks for letting me know. Odd that silentchest status would affect it, but oh well.

**Comment by smmmadden** [comment]
The other developer of QuickShop said the following to me regarding this and I confirmed that when QuickShop is used with OpenInv, this behavior can be seen. If I remove OpenInv and just have QuickShop, the left mouse button works as it should.  With it back in and with the default settings, I'm not able to break the chest with an axe.  So it does appear to still being caused by some event being passed on the left-click.  I'm not sure at this point if it is @[KaiKikuchi's](https://github.com/KaiKikuchi) issue to resolve, yours or both?

**Comment by Jikoo** [comment]
Posted my thoughts over on KaiKiKuchi/QuickShop#139. Technically I could handle it, but it would require a pretty hackish solution that would potentially cause inconsistencies for other plugins that also manually call the PlayerInteractEvent.
