### ISSUE TITLE
Chests play the open sound with /silentchest.

### ISSUE THREAD

**Issue by jacklollz2** [lishid/OpenInv#68]
Spigot 1.12.
Both me and the players hear the open sound when using /silentchest

**Comment by RoboMWM** [comment]
Plugins? Did you try with just Openinv installed?

**Comment by jacklollz2** [comment]
Tried it with only that plugin. Still having the issue.

**Comment by Jikoo** [comment]
I'll look into it when I get a chance, Mojang probably changed where the sound is played. Probably not tonight, maybe tomorrow depending on how some IRL plans end up finalizing.

**Comment by Jikoo** [comment]
Had a bit of a poke around, looks like the easiest fix is essentially one of the options I presented in Jikoo/OpenInv#11, forcing the player to be treated as a spectator when opening the container. It'll also simplify the process of dealing with shulker boxes, assuming I manage properly.

**Comment by Jikoo** [comment]
Actually, I cannot reproduce this. Please provide logs, exact server version, OpenInv version, and any other relevant information.

**Comment by jacklollz2** [comment]
OpenInv is the latest version. 3.2.1. Spigot is PaperSpigot latest, however default Spigot has the same issue.
Paper version git-Paper-1143 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[latest.log](https://pastebin.com/60Rx183x)

**Comment by Jikoo** [comment]
This is an issue with PaperSpigot, not Spigot. Default Spigot [does not have the same issue](https://youtu.be/MTNivD9dSKA).

**Comment by Jikoo** [comment]
I have not tested this on 1.11 and do not have time currently, but you're welcome to rename and use [OpenInv.zip](https://github.com/lishid/OpenInv/files/1122737/OpenInv.zip) - tested and working on both Spigot and PaperSpigot 1.12.

**Comment by jacklollz2** [comment]
Huh, I wonder why I had this issue on Spigot as well. I guess it was just because I updated asap since the server needs to be the latest version, and the snapshot build was the issue.
But thank you!

**Comment by Jikoo** [comment]
Works fine, [3.3.0](https://github.com/lishid/OpenInv/releases/tag/3.3.0) is now tagged. Will do a Bukkit release tonight, I'm pushing it already for leaving for work :V
