### ISSUE TITLE
OpenInv Not Loading with PaperSpigot (1.12.1)

### ISSUE THREAD

**Issue by CDAGaming** [lishid/OpenInv#72]
6:22:53 AM [INFO] [OpenInv] Enabling OpenInv v3.3.1-SNAPSHOT
6:22:53 AM [INFO] [OpenInv] Your version of CraftBukkit (v1_12_R1) is not supported.
6:22:53 AM [INFO] [OpenInv] If this version is a recent release, check for an update.
6:22:53 AM [INFO] [OpenInv] If this is an older version, ensure that you've downloaded the legacy support version.
6:22:53 AM [INFO] [OpenInv] Disabling OpenInv v3.3.1-SNAPSHOT

**Comment by Jikoo** [comment]
Where did you obtain your copy of OpenInv from?

**Comment by CDAGaming** [comment]
I compiled from Source and From https://github.com/lishid/OpenInv/issues/71 , both showed same result

**Comment by Jikoo** [comment]
When compiling, be sure to use a profile including the correct modules. Cannot reproduce using build from #71 and Paper build 1175.

**Comment by CDAGaming** [comment]
@Jikoo Here are the commands i have used so far to compile:

`mvn install -B`
`mvn compile`
`mvn install:install-file -Dpackaging=jar -Dfile=spigot-1.12.1-R0.1-SNAPSHOT.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.12.1-R0.1-SNAPSHOT`

**Comment by Jikoo** [comment]
To use the `all` profile, you need to have every version of CB/Spigot OpenInv can support installed, not just 1.12. Glad to know you've managed to figure it out.
