### ISSUE TITLE
Player loading & Advancements memory leak

### ISSUE THREAD

**Issue by Jikoo** [lishid/OpenInv#73]
Not sure if this was an issue with achievements, but advancements load each time a player is loaded, then never get garbage collected. Need to look into the logout process more to complete cleanup. Shouldn't present an issue to the average user, takes 1000+ player loads to make a real impact.

**Comment by RoboMWM** [comment]
Hmm I remember someone complaining about advancements with a heap dump in #spigot-dev but eventually he believes he resolved it by discovering someone spamming a packet and rate limiting said packet, as a resolution to his issue. (He also was doing NMS stuff.)

**Comment by Jikoo** [comment]
I found this to be an issue when loading players periodically for various checks, ended up having advancements consuming about 30% of the memory used. After reducing periodic checks, memory usage normalized. It's certainly not a concern for the average user, but it should definitely be fixed in case other plugins end up using Player objects provided by OpenInv. The server I'm currently working with has a rather small and consistent player base. I don't think anyone's been doing anything malicious, though I guess I can't entirely rule it out.

**Comment by RoboMWM** [comment]
Yea, he was also spawning entityplayers or something.

**Comment by Jikoo** [comment]
Not sure how this was handled back in 1.12 because I never invested the time to track it down, but in 1.15 there does not appear to be any special handling for advancements.

**Comment by Jikoo** [comment]
I had assumed this was resolved because I stopped encountering it in later versions, but according to [this post](https://www.spigotmc.org/threads/serverplayer-causing-memory-leak.573072/#post-4480216) it looks like this is as simple as releasing the player's advancement data.
