### ISSUE TITLE
OpenInv.exempt doesn't work when the player is offline

### ISSUE THREAD

**Issue by soliddanii** [lishid/OpenInv#74]
My moderator group has the permissions to open others inventories, but at the same time has the OpenInv.exempt so they can't open each other inventories. This works perfectly fine when the target is online, but when it is offline OpenInv.exempt doesn't work. I don't know if Im doing something wrong. 
Using paperspigot 1.12.1.
Thank you.

**Comment by Kakifrucht** [comment]
Not really a bug, since permission checks can only be done on online players.
One would have to individually hook permission plugins to check, which will not happen.
