### ISSUE TITLE
Default to anychest if permission given

### ISSUE THREAD

**Issue by lifehome** [lishid/OpenInv#76]
Can it be configurable default to anychest (on), if a player is given certain/specific permission?

**Comment by Jikoo** [comment]
Easy enough. I'll try to get to it this weekend, but no promises - my backlog's been piling up due to work.

**Comment by Jikoo** [comment]
Two days, two months, pretty much the same thing.

Nodes are `openinv.anychest.default` and `openinv.silentchest.default` currently, default false to keep existing behavior.
I'm not sure that I'll keep the paths the same - currently all OpenInv permissions have OpenInv containing caps. Most permissions plugins I've touched in recent years only deal in lowercase anyway, but it would be nice to keep everything simple and consistent just in case. May end up lowercasing everything and adding backwards compatibility perms. I'll make a decision and a release tomorrow.

**Comment by Jikoo** [comment]
Having reviewed the code, I'm not going to bother with lower case perms for now. It's simple enough to support both, but I don't want to do twice as many permissions checks just in case. When we next hit a major version bump I'll try to remember it. Nodes will be `OpenInv.any.default` and `OpenInv.silent.default`.

**Comment by Jikoo** [comment]
[3.3.1](https://github.com/lishid/OpenInv/releases/tag/3.3.1)
