### ISSUE TITLE
API for offline players doesn't work

### ISSUE THREAD

**Issue by SlimaKCoder** [lishid/OpenInv#77]
I'm trying to get inventory of online and offline players using OpenInv API, but it only works for online players. When I'm trying to get inventory of offline player I'm getting null :/

(getting openinv instance in main plugin class)
```java
 openinv = (OpenInv) getServer().getPluginManager().getPlugin("OpenInv");
```

{trying to get player inv by uuid)
```java
UUID uuid = UUID.fromString(uuid_string);
Player player = Bukkit.getOfflinePlayer(uuid).getPlayer();

ISpecialPlayerInventory openinv_inv = openinv.getSpecialInventory(player, player.isOnline()); //null point exeption
Inventory inv = openinv_inv.getBukkitInventory();
```

Note: opeinv.getInventory() also works only for online players

(probably not related, because this code works for online players, but I'm executing it as async task)
```java
Bukkit.getScheduler().runTaskAsynchronously(this, new Runnable() {
    @Override
    public void run() {
        //code
    }
});
```

**Comment by Jikoo** [comment]
Well, yeah, you're using `OfflinePlayer#getPlayer` to obtain your Player object. That returns null for offline players.
```Java
Player player = openInv.loadPlayer(Bukkit.getOfflinePlayer(uuid));
```
If you want to support name input as well:
```Java
Player player = openInv.loadPlayer(openInv.matchPlayer(uuidString));
```

**Comment by Jikoo** [comment]
I also strongly recommend you only load the player async, then open the inventory on the main thread, you're opening yourself to concurrency issues otherwise.

**Comment by SlimaKCoder** [comment]
Thank you, but I don't want to manipulate inventories for now, only read them :)
