### ISSUE TITLE
OpenInv is Overriding too Many Commands

### ISSUE THREAD

**Issue by Techno3600** [lishid/OpenInv#79]
Hello,

I installed OpenInv a long time ago, but when I try to do /ac or /sc for other commands like stuff in Essentials it this plugin overrides it and therefore cool features from other plugins cannot be used because OpenInv overrides every other plugin.
My solution is to do something like this in the config. 
 CompatibilityOptions:
    # The event priority which OpenInv should use for the specific event.
    # If another plugin overrides SV's join/leave settings, setting the priorities to MONITOR can help.
    # Allowed values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
   CommandImput: HIGH # <- Set this to "HIGH" if you use Essentials to modify stuff
    CommandImput: NORMAL

**Comment by Kakifrucht** [comment]
Just use ``/pluginname:command`` for overriden commands, or spell them out instead of using short aliases. For Essentials commands you can always prefix your command with an ``e``, e.g. instead of ``/home`` ``/ehome``.

**Comment by RoboMWM** [comment]
Use `commands.yml` to setup command/command aliases to whatever you want.

**Comment by Jikoo** [comment]
As Robo said, use your [commands.yml](https://bukkit.gamepedia.com/Commands.yml) to set up command overrides. This is a default Bukkit feature.
