### ISSUE TITLE
Console Error on 3.3.1

### ISSUE THREAD

**Issue by MysticCity** [lishid/OpenInv#81]
08.11.2017 14:00:59 [SEVERE] Could not pass event PlayerInteractEvent to OpenInv v3.3.1
08.11.2017 14:00:59 org.bukkit.event.EventException: null
08.11.2017 14:00:59 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
08.11.2017 14:00:59 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:00:59 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:01:00 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:01:00 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:01:00 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
08.11.2017 14:01:00 Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.lishid.openinv.util.Permissions
08.11.2017 14:01:00 	at com.lishid.openinv.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:65) ~[?:?]
08.11.2017 14:01:00 	at sun.reflect.GeneratedMethodAccessor316.invoke(Unknown Source) ~[?:?]
08.11.2017 14:01:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
08.11.2017 14:01:00 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
08.11.2017 14:01:00 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
08.11.2017 14:01:00 	... 17 more

**Comment by Jikoo** [comment]
[3.3.2](https://github.com/lishid/OpenInv/releases/tag/3.3.2)

**Comment by Jikoo** [comment]
I've also deleted the compiled files from the releases here and Bukkit, ideally no one else will be affected. Thanks for letting me know.
