### ISSUE TITLE
OpenInv Jar rewritten at restart

### ISSUE THREAD

**Issue by helyang** [lishid/OpenInv#82]
I'm running a KCauldron 1.7.10 server and every time the server restarts, OpenInv jar gets rewritten and is only 178 bytes. It must be added again before it'll work.

**Comment by RoboMWM** [comment]
1.7.10 isn't supported - you can use an older version but other than that, seems like it's a kcauldron issue since OpenInv doesn't modify itself afaik.

**Comment by Jikoo** [comment]
OpenInv doesn't contain any kind of updater or anything else that would modify the jar. Sounds like a KCauldron or other plugin issue, sorry.
