### ISSUE TITLE
Openinv messes up hotbar

### ISSUE THREAD

**Issue by GrayChief** [lishid/OpenInv#83]
When I do /opening on a player it switches their hot bar into their inventory (1.12.1)

**Comment by RoboMWM** [comment]
Uh wut.
- Please provide more details. What plugin is in charge of /opening?
- What do you mean by "switches their hot bar into their inventory"? (Does it go in any specific slot, only some items, etc.?)
- Spigot, orebfuscator, etc. would be helpful

**Comment by GrayChief** [comment]
I'm not too sure what you mean I'm using spigot and It transfers the whole hotbar into the top row of the inventory

**Comment by RoboMWM** [comment]
do `/version` and `/version orebfuscator` and paste the output here.

Also what plugin does /opening ?

**Comment by GrayChief** [comment]
no plugin runs by that name, I just downloaded Openinv stuck it in my plugins folder and restarted the server it worked fine until yesterday

**Comment by Jikoo** [comment]
What changed yesterday? Also, versions please. 1.12.1 alone isn't enough to go on, unfortunately.

**Comment by Jikoo** [comment]
Closing due to lack of response.
