### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by RickyTheSeaCat** [lishid/OpenInv#84]
Hey I have an issue with the plugin. So, players with the permissions needed to use /openinv can open their own inventory and duplicate their items by putting them in their inventory and hitting the escape key really quickly. I tried it myself and got a stack of diamond blocks out of one diamond block.

**Comment by Jikoo** [comment]
Can't reproduce. Server version/OpenInv version?

The perm `OpenInv.openself` exists, so you can use that as a bandaid.

**Comment by RickyTheSeaCat** [comment]
Ah, thank you! I couldn't find that :D

**Comment by Jikoo** [comment]
Still awaiting replication information. You weren't in creative, were you?

**Comment by RickyTheSeaCat** [comment]
No, I was in survival. However, it seems to just be a bug caused by one of
my custom plugins. Sorry for the trouble!

**Comment by Jikoo** [comment]
Ah, okay, thanks. I know there used to be a couple bugs related to it, but I was fairly sure they'd all been ironed out.
