### ISSUE TITLE
OP user ignores permission nodes

### ISSUE THREAD

**Issue by k0nker** [lishid/OpenInv#85]
I have created a permission group that removes things from OP, it works since plugins just search for the permission to give access to a command.  However, this plugin is the only one that is ignoring the removal of a node, specifically openinv.override.

Essentials, CorePortect, WorldGuard, WorldEdit, etc, all listen to the perm group that gives their perms a false flag and denies the ability to use their commands to those with OP, but OpenInv is letting anyone with OP override the .exempt node on players.

As for why I did this, I wanted to give my staff members the ability to utilize command blocks, but nothing extra that op gives (like \*.* permissions).  Is there a chance you can add in the ability to not default the permissions to OP users?  Or if there's an ISOP() boolean in the permission check, maybe have a way to turn it off in the config?

**Comment by RoboMWM** [comment]
Set negation nodes if you don't want your ops to actually be ops...

**Comment by Jikoo** [comment]
Guess we'll have to actually check what each PermissionAttachment sets values to rather than using a basic permissions check.

As a bandaid, you can negate `OpenInv.*`

**Comment by k0nker** [comment]
I already attempted to just negate openinv.* in the permissions and it also did not work.

**Comment by Jikoo** [comment]
Oops, you'll also need to negate `*`. I really hate wildcards.

**Comment by Jikoo** [comment]
Please try [OpenInv.zip](https://github.com/lishid/OpenInv/files/2041557/OpenInv.zip)

**Comment by Jikoo** [comment]
[3.3.4](https://github.com/lishid/OpenInv/releases/tag/3.3.4) contains this fix. I'm assuming it works as intended due to the lack of response.
