### ISSUE TITLE
/anychest or /silentchest toggled ON causes two chests to open in 1.13

### ISSUE THREAD

**Issue by SimonOrJ** [lishid/OpenInv#87]
In OpenInv version 3.3.4 on 1.13, opening two single chests next to each other opens both chests.  When a double chest and a single chest are next to each other, both opens when opening the single chest.

**Comment by Jikoo** [comment]
Should be addressed in 59a8ed70, will ideally find some time to test tonight.

**Comment by Jikoo** [comment]
I don't see myself getting to testing today after all. You're welcome to try [OpenInv.zip](https://github.com/lishid/OpenInv/files/2276197/OpenInv.zip) or hang tight for a while.

**Comment by Jikoo** [comment]
[3.3.5](https://github.com/lishid/OpenInv/releases/tag/3.3.5)
