### ISSUE TITLE
OpenInv is not being recognized.

### ISSUE THREAD

**Issue by ZuneGamer** [lishid/OpenInv#88]
Hello,
I'm trying to make use of one of the older OpenInv builds (2.0.9) for 1.6.4.  I am running the newest version of the ATL Yogscast Complete Pack Server (1.6.4), and once the server boots and I log in, none of OpenInv's commands work, and the server seems to not even recognize the plugin.  This sounds like a problem on the servers end, but is there anyway you might be able to help me troubleshoot this?  I have not set up any permissions, and have installed the plugin just like I would any other.
![ca7a8041b556dcc23a626e8eb15c983a](https://user-images.githubusercontent.com/11763391/44028523-00b9e078-9eaf-11e8-9b78-0741c3712670.png)
![b2f222ba8a825ba2be8cc5a02a495519](https://user-images.githubusercontent.com/11763391/44028525-03a1f5b4-9eaf-11e8-98a4-469f9a3f45a0.png)

**Comment by Jikoo** [comment]
Are you running Cauldron? Forge does not support Bukkit plugins.

**Comment by ZuneGamer** [comment]
Yup that's it, thank you.
