### ISSUE TITLE
OpenInv issue with EpicHoppers

### ISSUE THREAD

**Issue by ChimpGamer** [lishid/OpenInv#91]
Hey there,

I have an issue with the filter of EpicHoppers when OpenInv is running on the server.
It seems like it prevents EpicHoppers from saving the Inventory when it's being closed.

I hope there is something to do about this issue because OpenInv is kind of an essential plugin to have.

Thanks,

ChimpGamer

**Comment by RoboMWM** [comment]
What exactly is happening? Can you give the steps that cause the issue?

**Comment by ChimpGamer** [comment]
Well, when I open the Filter in the Hopper plugin and place my item into the filter and close the inventory it won't save the filter when OpenInv is on the server. When OpenInv isn't on the server the filter saves just fine when I close the inventory.

I hope I've informed you more then enough with this information.

**Comment by Jikoo** [comment]
As this appears to be some weird compatibility issue on EpicHoppers' end, I'm going to close it. Let me know if this is still a concern.
