### ISSUE TITLE
Suggestions for inventories

### ISSUE THREAD

**Issue by ArtelGG** [lishid/OpenInv#92]
**Here's a list of things you guys should try to add for online players' inventories:**
1. Show what the player has attached to their cursor;
![image](https://user-images.githubusercontent.com/21347579/46597303-969fad00-caad-11e8-9add-d9df61401072.png)
> 1.a Just in case it's not already a thing, the player's off-hand slot for newer versions.
2. Show what the user has in their crafting inventory, including the result slot;
![image](https://user-images.githubusercontent.com/21347579/46597417-feee8e80-caad-11e8-9a87-1c0bd7262376.png)
3. Have an item formatted with the user's potion effects, UUID, perhaps their hunger and saturation, gamemode, location, etc.

**Comment by Jikoo** [comment]
1 and 2 I'll look into. 3 is included in #54 to a degree, probably more in line for an addon. Offhand slot is already handled.

**Comment by ArtelGG** [comment]
> 
> 
> 1 and 2 I'll look into. 3 is included in #54 to a degree, probably more in line for an addon. Offhand slot is already handled.
> I won't show the crafting result slot - that should not be insertable by the client. If it is, that's really on the server implementation to prevent. I believe actual anticheat features to be outside of the scope of OI.

Sounds good. If the crafting result slot is just a simple grab of a slot ID think you could implement it anyway?

**Comment by RoboMWM** [comment]
There's no reason to show the crafting result slot if the client can't store an item in there, which I see no reason why it would be able to.

**Comment by Jikoo** [comment]
>Sounds good. If the crafting result slot is just a simple grab of a slot ID think you could implement it anyway?

After some thought, no.
It looks simple, but then you start to consider what do we do if the viewer modifies the result. Do we rewrite all of OpenInv's click handling so the viewer can't modify the result slot? Do we "craft" the item, and do we then have to manually include all crafting logic? Gets messy and time-consuming very quickly.

**Comment by Jikoo** [comment]
OI now offers a view of the crafting slots and cursor. If the player's inventory is the expected size, a view of the result is also available. The result view is only for clarity of what the player is doing, and is not editable.
