### ISSUE TITLE
Loss of items with OpenInv 3.3.7

### ISSUE THREAD

**Issue by jovanmanic** [lishid/OpenInv#98]
Greetings,

Our players are exposed to loss of items when transferring items from inventory to enderchest when theirs connection is about to drop. After removal of OpenInv.jar from our plugins folder this hadn't been the case. We had been removing OpenInv from our servers one at a time leaving only one server with it's .jar running and that was the only server that had our players complaining of still losing their items, so that's how we determined that it is it that's causing this problem.

Old OpenINV seem not to be causing this, but despite that it pops lots of errors in console randomly.

Thanks in advance!

**Comment by Jikoo** [comment]
OpenInv version? Server implementation? What you're describing shouldn't be possible using exclusively OpenInv. What does old OpenInv mean?

**Comment by jovanmanic** [comment]
OpenInv version 3.3.7

We use that plugin on every subserver on our network and all subservers we have different plugins...

Old OpenInv means that we used version 3.3.6! With that version everything worked okay but in console we had some bugs!

**Comment by Jikoo** [comment]
The only difference between 3.3.6 and 3.3.7 is 4f4d46974, which only affects shulker boxes and anychest. This could possibly be another plugin using OpenInv's API to load players, but if downgrading to 3.3.6 fixed it, the issue was never OpenInv :\

**Comment by baticag** [comment]
It's the problem with same 3.3.6 and 3.3.7. Nothing is using OpenInv API. I think the problem is with Java 9+. Can you please look more into this problem?

**Comment by Jikoo** [comment]
You're really not giving me anything to work with here, no evidence of issues beyond hearsay. I need actual information to do anything. You haven't even told me what version your servers are, let alone other plugins present.

**Comment by baticag** [comment]
I understand, so here is info:
It happens on all servers never mind what kind of plugins server has. It only happens when OpenInv is in plugins list. After we remove it everything is okay.

We tested it on all of our servers with Java 10
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

and PaperSpigot 1.13.2
[23:32:14 INFO]: This server is running Paper version git-Paper-566 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:32:14 INFO]: Previous version: git-Paper-556 (MC: 1.13.2)
[23:32:14 INFO]: Checking version, please wait...
[23:32:14 INFO]: You are running the latest version

**Comment by RoboMWM** [comment]
Try testing with just openinv installed? Even if the servers don't have the exact same plugin setup I bet they all share some set of plugins.

**Comment by baticag** [comment]
Here's a list of plugins servers share:
```
AnimatedNames
ArmorStandTools
BungeeTabListPlus
ChatControl
ChestCommands
ClearLag
CrateReloaded
EditableSign
Essentials
EssentialsChat
EssentialsSpawn
ExecuteEverywhere
FeatherBoard
HolographicDisplays
LuckPerms
MVdWPlaceholderAPI
NickRemover
PlayerPoints
ProtocolLib
SkinsRestorer
Vault
WorldEdit
WorldGuard
Yamler
```

Testing without proxy would currently be impossible in our setup :/ Also cannot start server with only OpenInv since we don't know how to reproduce this bug yet. It just happens random.

**Comment by Jikoo** [comment]
All right, appreciate the additional info. Any errors in console around times when players complain of losing ender chest contents? Java 9 broke the reflection used to mirror contents into our implementation's inventory, could be that someone looked in their ender chest and ended up overwriting it with nothing.

**Comment by baticag** [comment]
As far as I monitored, there are no errors in console and logs.
Can you release some version for Java 9+?

**Comment by baticag** [comment]
Any update on this?

**Comment by RoboMWM** [comment]
Until more specific info can be gathered about this (primarily how to reproduce) there isn't anything new to report on...

**Comment by Jikoo** [comment]
Have you had any issues since swapping to a version supporting Java 9?

**Comment by Jikoo** [comment]
Since there's been no response and the issue cannot be reliably reproduced, I'm going to assume that supporting Java 9 fixed this.
