### ISSUE TITLE
/silentchest plays open sound with regular/trapped chests (tested on 3.3.2 and 3.3.7)

### ISSUE THREAD

**Issue by chrisjk7** [lishid/OpenInv#99]
The /silentchest command kinda of works, but only on ender chests. Whenever I open a regular or trapped chest, I always hear the sound of the chest opening and closing fast.

This was tested on versions 3.3.2 and 3.3.7 on BeerSpigot

**Comment by Jikoo** [comment]
Version of BeerSpigot? Also, can you link the BeerSpigot repo? Coming up dry on a quick search for it.

**Comment by Jikoo** [comment]
BeerSpigot appears to be a premium fork of Spigot. Can't support what I can't investigate, and there's no followup from OP.
